// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using AES.Dispatcher.Models;

// Do not modify this file. This code was generated by RAML Server Scaffolder

namespace AES.Dispatcher
{
    [RoutePrefix("v1/dispatcher")]
    public partial class v1DispatcherController : ApiController
    {


/// <summary>
		/// Retorna el valor a pagar asociado a un número de referencia - /consultar/{numeroReferencia}
		/// </summary>
		/// <param name="numeroReferencia"></param>
		/// <returns>MultipleDispatcherConsultarNumeroReferenciaGet</returns>
        [ResponseType(typeof(MultipleDispatcherConsultarNumeroReferenciaGet))]
        [HttpGet]
        [Route("consultar/{numeroReferencia}")]
        public virtual async Task<IHttpActionResult> GetBase([FromUri] string numeroReferencia)
        {
            // Do not modify this code
                        return await ((Iv1DispatcherController)this).Get(numeroReferencia);
                    }

/// <summary>
		/// /pagar
		/// </summary>
		/// <param name="pago"></param>
		/// <returns>MultipleDispatcherPagarPost</returns>
        [ResponseType(typeof(MultipleDispatcherPagarPost))]
        [HttpPost]
        [Route("pagar")]
        public virtual async Task<IHttpActionResult> PostBase(Models.Pago pago)
        {
            // Do not modify this code
                        return await ((Iv1DispatcherController)this).Post(pago);
                    }

/// <summary>
		/// /compensar
		/// </summary>
		/// <param name="pago"></param>
		/// <returns>MultipleDispatcherCompensarPost</returns>
        [ResponseType(typeof(MultipleDispatcherCompensarPost))]
        [HttpPost]
        [Route("compensar")]
        public virtual async Task<IHttpActionResult> PostCompensarBase(Models.Pago pago)
        {
            // Do not modify this code
                        return await ((Iv1DispatcherController)this).PostCompensar(pago);
                    }
    }
}
