// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace AES.Dispatcher.Models
{
    /// <summary>
    /// Multiple Response Types Resultado, Resultado404
    /// </summary>
    public partial class MultipleDispatcherPagarPost
    {
        


        public Resultado Resultado { get; set; }


        public Resultado Resultado404 { get; set; }
    } // end class

} // end Models namespace

